# SPDX-License-Identifier: MPL-2.0

"""The table of resources that the app bundle holds.

`Sources/ArknightsClient/Shared/Resources/BundledResource.swift` names the resources
that the app reads. This table names the same resources with their sources and
formats. `registry_drift` reports every difference between the two.

Encoding rule: a file that the build copies verbatim from the repository stays
`identity`, so the bundle holds the same bytes as the source. A document that the
build generates uses `deflate` (raw deflate of UTF-8 text).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from lib.licenses import BUNDLE_NOTICES_NAME
from lib.project_config import ProjectConfiguration

SWIFT_REGISTRY = Path("Sources/ArknightsClient/Shared/Resources/BundledResource.swift")

ORIGIN_APP = "app"
ORIGIN_PACKAGE = "package"
IDENTITY = "identity"
DEFLATE = "deflate"

_DECLARATION = re.compile(
    r"static\s+let\s+\w+\s*=\s*BundledResource\(\s*"
    r'(?P<kind>file|directory):\s*"(?P<path>[^"]+)",\s*'
    r"origin:\s*\.(?P<origin>app|package)"
    r"(?:,\s*encoding:\s*\.(?P<encoding>identity|deflate))?\s*\)"
)

ResourceKey = tuple[str, str, str, str]


@dataclass(frozen=True)
class StagedResource:
    """One file or directory in `Contents/Resources`.

    `source` is the repository path that the build copies, or `None` when the
    build generates the resource. `swift_reads` is true when the app loads the
    resource by name, so `BundledResource.swift` must list it.
    """

    path: str
    kind: str
    origin: str
    encoding: str = IDENTITY
    source: str | None = None
    swift_reads: bool = True

    @property
    def key(self) -> ResourceKey:
        return (self.path, self.kind, self.origin, self.encoding)


FIXED_RESOURCES = (
    StagedResource("LICENSE", "file", ORIGIN_APP, source="LICENSE"),
    StagedResource("CHANGELOG.md", "file", ORIGIN_APP, source="CHANGELOG.md"),
    StagedResource("RUNTIME.json", "file", ORIGIN_APP, source="runtime.json"),
    # Generated by `lib.licenses.stage_bundle`.
    StagedResource(BUNDLE_NOTICES_NAME, "file", ORIGIN_APP, DEFLATE),
    StagedResource(
        "SupportArticles", "directory", ORIGIN_APP, source="docs/help/errors"
    ),
    # Built by `build_compatibility.py` and embedded from the runtime archive.
    StagedResource("Compatibility", "directory", ORIGIN_APP),
    StagedResource("Runtime", "directory", ORIGIN_APP),
)


def staged_resources(configuration: ProjectConfiguration) -> tuple[StagedResource, ...]:
    """Return every resource of the bundle."""
    icon_file = configuration.product.icon_file
    icon_filename = icon_file if Path(icon_file).suffix else f"{icon_file}.icns"
    # Info.plist names the icon, so the app never loads these two by name.
    icons = (
        StagedResource(
            icon_filename,
            "file",
            ORIGIN_APP,
            source=f"Resources/{icon_filename}",
            swift_reads=False,
        ),
        StagedResource(
            "Assets.car",
            "file",
            ORIGIN_APP,
            source="Resources/Assets.car",
            swift_reads=False,
        ),
    )
    package = tuple(
        StagedResource(
            path.name,
            "directory" if path.is_dir() else "file",
            ORIGIN_PACKAGE,
            source=str(path.relative_to(configuration.project_directory)),
        )
        for path in configuration.copied_resource_source_paths
    )
    return (*icons, *FIXED_RESOURCES, *package)


def swift_registry(source: str) -> tuple[ResourceKey, ...]:
    """Parse the resource declarations of `BundledResource.swift`."""
    return tuple(
        (
            match["path"],
            match["kind"],
            match["origin"],
            match["encoding"] or IDENTITY,
        )
        for match in _DECLARATION.finditer(source)
    )


def registry_drift(
    configuration: ProjectConfiguration, swift_source: str | None = None
) -> list[str]:
    """Return the differences between the Swift registry and the staging table."""
    if swift_source is None:
        swift_source = (configuration.project_directory / SWIFT_REGISTRY).read_text(
            encoding="utf-8"
        )
    declared = swift_registry(swift_source)
    problems: list[str] = []
    paths = [entry[0] for entry in declared]
    if len(paths) != len(set(paths)):
        problems.append(f"{SWIFT_REGISTRY} declares a path more than once")

    staged = staged_resources(configuration)
    staged_paths = [resource.path for resource in staged]
    if len(staged_paths) != len(set(staged_paths)):
        problems.append("the staged resources contain duplicate paths")

    expected = {resource.key for resource in staged if resource.swift_reads}
    for entry in sorted(set(declared) - expected):
        problems.append(
            f"{SWIFT_REGISTRY} lists a resource the build does not stage: {entry}"
        )
    for entry in sorted(expected - set(declared)):
        problems.append(
            f"the build stages a resource {SWIFT_REGISTRY} does not list: {entry}"
        )
    return problems
